"""00004-Renombrado de la columna username

Revision ID: 594cfbe565e3
Revises: f68f8e828394
Create Date: 2026-04-11 20:11:02.658718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '594cfbe565e3'
down_revision = 'f68f8e828394'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=50), nullable=False))
        batch_op.drop_constraint(batch_op.f('usuarios_useranme_key'), type_='unique')
        batch_op.create_unique_constraint(None, ['username'])
        batch_op.drop_column('useranme')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('useranme', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint(batch_op.f('usuarios_useranme_key'), ['useranme'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('username')

    # ### end Alembic commands ###
